# Generated by Django 5.2.4 on 2026-03-18 07:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_booking_is_paid_booking_payment_intent_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['is_paid'], name='core_bookin_is_paid_edae2c_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['brand'], name='core_car_brand_03cde5_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['name'], name='core_car_name_c48592_idx'),
        ),
    ]
