# Generated by Django 5.2.4 on 2026-03-18 07:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_booking_core_bookin_is_paid_edae2c_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['created_at'], name='core_bookin_created_f24220_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['created_at'], name='core_car_created_0235e4_idx'),
        ),
    ]
