# Generated by Django 5.2.4 on 2026-03-18 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_festivaloffer_booking_gst_amount_booking_gst_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='free_km',
            field=models.IntegerField(blank=True, default=150, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('Maruti Suzuki', 'Maruti Suzuki'), ('Tata', 'Tata'), ('Hyundai', 'Hyundai'), ('Mahindra', 'Mahindra'), ('Kia', 'Kia'), ('Toyota', 'Toyota'), ('Honda', 'Honda'), ('Volkswagen', 'Volkswagen'), ('Skoda', 'Skoda'), ('MG', 'MG'), ('BMW', 'BMW'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Audi', 'Audi'), ('Porsche', 'Porsche'), ('Ferrari', 'Ferrari'), ('Lamborghini', 'Lamborghini'), ('Rolls Royce', 'Rolls Royce'), ('Bentley', 'Bentley'), ('Tesla', 'Tesla'), ('Range Rover', 'Range Rover')], max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('Compact SUV', 'Compact SUV'), ('SUV', 'SUV'), ('Premium SUV', 'Premium SUV'), ('Luxury Sedan', 'Luxury Sedan'), ('Ultra Luxury', 'Ultra Luxury'), ('Electric', 'Electric'), ('MPV', 'MPV'), ('Off-road SUV', 'Off-road SUV'), ('Micro SUV', 'Micro SUV'), ('Hybrid', 'Hybrid')], max_length=20),
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_info', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
