# Generated by Django 5.2.4 on 2026-03-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='dropoff_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_date',
            field=models.DateTimeField(),
        ),
    ]
