# Generated by Django 5.2.4 on 2026-03-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pendingbooking_promocode_delete_festivaloffer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='features',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
