# Generated by Django 5.2.12 on 2026-03-24 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_car_features'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingBooking',
        ),
    ]
