# Generated by Django 5.2.4 on 2026-03-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_car_fuel_type_alter_car_price_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='abandoned_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
