# Generated by Django 5.2.4 on 2026-03-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_booking_dropoff_time_booking_pickup_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
