# Generated by Django 5.2.4 on 2026-03-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_booking_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_reference',
            field=models.CharField(blank=True, default='', editable=False, max_length=12, null=True),
        ),
    ]
