# Generated by Django 5.2.4 on 2026-03-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='license_image',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
