# Generated by Django 5.2.4 on 2026-03-18 12:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_is_verified_userprofile_license_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Aadhaar number must be exactly 12 digits')]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^[A-Z]{5}[0-9]{4}[A-Z]{1}$', 'Enter a valid PAN card number (e.g., ABCDE1234F)')]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\+91[6-9]\\d{9}$', 'Enter a valid Indian mobile number starting with +91')]),
        ),
    ]
