# Generated by Django 5.2.12 on 2026-03-24 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_aadhaar_number_userprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\+91[6-9]\\d{9}$', 'Enter a valid Indian mobile number starting with +91')]),
        ),
    ]
